const errorCodes = {
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  BLOCK_NOT_FOUND: 'BLOCK_NOT_FOUND',
  INVALID_BLOCK_SPLIT: 'INVALID_BLOCK_SPLIT',
  INVALID_REORDER: 'INVALID_REORDER',
  SHARE_NOT_FOUND: 'SHARE_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR'
};

export default errorCodes;
